PowerQualityManageService/Controllers/DataAcquisitionController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using PowerQualityManageService.Core.Services.Abstract;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PowerQualityManageService.Controllers;

[ApiController]
[Route("[controller]")]
public class DataAcquisitionController : Controller
{
    private readonly IDataAcquisitionService _dataManagementService;
    public DataAcquisitionController(IDataAcquisitionService service)
    {
        _dataManagementService = service;
    }

    [HttpGet]
    public async Task<ActionResult> Index()
    {
        ViewBag.CurrentArea = "Import danych";
        var points = await _dataManagementService.GetMeasuringPoints();
        var res = points.Select(x => new SelectListItem { Text = x, Value = x }).ToList();
        ViewBag.MeasuringPoints = res;
        return View();
    }

    [HttpPost]
    [Route("Upload")]
    public async Task<ActionResult<string?>> Upload([FromForm] IFormFile fileInput)
    {
        string? res = await _dataManagementService.Upload(fileInput);
        if (res != null) { ViewBag.fileName = res; }
        return res == null ? NotFound() : Ok(res);
    }

    [HttpGet]
    [Route("Headers")]
    public async Task<ActionResult<DataTable?>> Headers([FromQuery] string fileName)
    {
        var dt = await _dataManagementService.LoadParseHeaders(fileName);
        if (dt != null) { ViewBag.headers = dt; }
        return dt == null ? NotFound() : Ok(dt);
    }

    [HttpPost]
    [Route("Save")]
    public async Task<ActionResult<int>> Save([FromForm] string fileName, [FromForm] string measuringPoint)
    {
        int res = await _dataManagementService.Save(fileName, measuringPoint);
        return Ok(res);
    }

    //    [HttpPut]
    //    public ActionResult ModifyHeader(ColumnHeader header)
    //    {
    //        throw new NotImplementedException();
    //    }

    //    [HttpPost]
    //    [Route("Test")]
    //    public ActionResult Test()
    //    {

    //        return Ok();
    //    }
}

PowerQualityManageService/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PowerQualityManageService.Core.Helpers;
using PowerQualityManageService.Core.Services.Abstract;
using PowerQualityManageService.Model.Models;
using PowerQualityManageService.Models;
using SharpCompress.Common;
using System.Diagnostics;

namespace PowerQualityManageService.Controllers;

[ApiController]
[Route("[controller]")]
public class ReportController : Controller
{
    private readonly IReportService _reportService;
    public ReportController(IReportService reportService)
    {
        _reportService = reportService;
    }

    public async Task<IActionResult> Index()
    {
        ViewBag.CurrentArea = "Raporty";
        ViewBag.Reports = await _reportService.GetReports();
        return View();
    }

    [HttpGet]
    [Route("Generate")]
    public async Task<ActionResult> Generate()
    {
        var tmpls = await _reportService.GetTemplatesNames();
        var resTmpls = tmpls.Select(x => new SelectListItem { Text = x, Value = x }).ToList();
        ViewBag.Templates = resTmpls;

        var points = await _reportService.GetMeasuringPoints();
        var resPoints = points.Select(x=> new SelectListItem { Text = x, Value = x }).ToList();
        ViewBag.MeasuringPoints = resPoints;

        var startEndDate = await _reportService.GetStartEndDate();
        ViewBag.StartDate = startEndDate.Item1;
        ViewBag.EndDate = startEndDate.Item2;
        return View();
    }

    [HttpPost]
    [Route("Generate")]
    public async Task<ActionResult<string>> Generate([FromForm]AddReportModel model)
    {

        string templateName = model.Template;
        ResultDefinition resultDefinition = new ResultDefinition()
        {
            DateFrom = model.DateFrom,
            DateTo = model.DateTo, 
            MeasuringPoint = model.MeasuringPoint           
        };
        string reportName = model.Name;
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();

        await _reportService.GenerateReport(templateName, resultDefinition,reportName);
        
        stopwatch.Stop();
        TimeSpan czasWykonania = stopwatch.Elapsed;
        Console.WriteLine("Czas wykonania akcji w controllerze: " + czasWykonania);

        
        ViewBag.Reports = await _reportService.GetReports();
        return View("Index");
    }

    [HttpGet]
    [Route("Preview")]
    public async Task<ActionResult> Preview(string fileName)
    {
        string filepath = fileName.ToFilePath();
        _reportService.PreviewReport(filepath);
        ViewBag.Reports = await _reportService.GetReports();
        return View("Index");
    }

    [HttpGet]
    [Route("SendMail")]
    public ActionResult SendMail(string fileName)
    {
        ViewBag.FileName = fileName;
        return View();
    }

    [HttpPost]
    [Route("SendMail")]
    public async Task<ActionResult> SendMail([FromForm]MailModel model)
    {
        bool result = await _reportService.SendMail(model);
        ViewBag.Reports = await _reportService.GetReports();// MockModels();
        return View("Index");
    }

    [HttpGet]
    [Route("Download")]
    public async Task<ActionResult> Download(string fileName)
    {
        string filepath = fileName.ToFilePath();
        byte[] file = await _reportService.Download(filepath);
        Response.Headers.Clear();
        Response.Headers.Add("Content-Disposition", $"attachment; filename=\"{filepath}\"");
        return File(file, "application/octet-stream");
    }

    [HttpGet]
    [Route("Delete")]
    public async Task<ActionResult> Delete(string fileName)
    {
        bool result = await _reportService.Delete(fileName);
        if (result == false) return View("Error");
        ViewBag.Reports = await _reportService.GetReports();
        return View("Index");
    }

    private List<ReportDTOModel> MockModels()
    {
        return new List<ReportDTOModel>() {
            new ReportDTOModel() { Name = "a", Template = "b", DateRange = "c", MeasuringPoint = "d" },
            new ReportDTOModel() { Name = "a2", Template = "b2", DateRange = "c2", MeasuringPoint = "d2" }};
    }
}

PowerQualityManageService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PowerQualityManger</title>

    <link href="~/img/brand.png" rel="icon" type="image/png">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet"/>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    

    <link type="text/css" href="~/css/argon.css?v=1.2.0" rel="stylesheet" asp-append-version="true">

    @RenderSection("Styles", required: false)
    @RenderSection("HeadScripts", required: false)
</head>
<body>
    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PowerQualityManger</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <partial name="_Sidenav" />
    <div class="main-content">
        <partial name="Topnav/_Topnav" />
        <div class="container">
            <div class="empty-space"></div>
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PowerQualityManageService/Views/Shared/_Loading.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div id="loading-popup" title="Ładowanie...">
    <p>Proszę czekać...</p>
</div>

PowerQualityManageService/Views/Shared/_Sidenav.cshtml
<!-- Sidenav -->
<nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">

        <!-- Brand -->
        <div class="sidenav-header  align-items-center">
            <a class="navbar-brand" href="javascript:void(0)">
                @*<img src="~/img/brand.png" class="navbar-brand-img" alt="...">*@
                <a class="h4 mb-0 text-black d-none d-lg-inline-block" href="/">PowerQualityManager</a>
            </a>
        </div>
        <div class="navbar-inner">
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">

                <!-- Collapse header -->
                <div class="navbar-collapse-header d-md-none">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            <a href="/">
                               
                            </a>
                        </div>
                        <div class="col-6 collapse-close">
                            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                                <span></span>
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Navigation -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">
                            <img alt="Image placeholder" src="~/img/home.png" width="32" height="32">
                            <i class="text-primary"></i> Strona Główna
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="DataAcquisition" asp-action="Index">
                            <img alt="Image placeholder" src="~/img/data.png" width="32" height="32">
                            <i class="text-orange"></i> Import Danych
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Preview" asp-action="Index">
                            <img alt="Image placeholder" src="~/img/preview.png" width="32" height="32">
                            <i class="text-orange"></i> Podgląd
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Template" asp-action="Index">
                            <img alt="Image placeholder" src="~/img/template.png" width="32" height="32">
                            <i class="text-orange"></i> Szablony
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Report" asp-action="Index">
                            <img alt="Image placeholder" src="~/img/report.png" width="32" height="32">
                            <i class="text-orange"></i> Raporty
                        </a>
                    </li>
                </ul>

                
            </div>
        </div>
    </div>

</nav>