PowerQualityManageService/Controllers/PreviewController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PowerQualityManageService.Core.Repositories.Abstract;
using PowerQualityManageService.Core.Services.Abstract;
using PowerQualityManageService.Core.Services.Concrete;
using System.Data;

namespace PowerQualityManageService.Controllers;

[ApiController]
[Route("[controller]")]
public class PreviewController : Controller
{
    private readonly IDataService _dataManagementService;

    public PreviewController(IDataService dataManagementService)
    {
        _dataManagementService = dataManagementService;
    }

    public async Task<IActionResult> Index()
    {
        ViewBag.CurrentArea = "Podgląd";
        var points = await _dataManagementService.GetMeasuringPoints();
        var res = points.Select(x => new SelectListItem { Text = x, Value = x }).ToList();
        ViewBag.MeasuringPoints = res;
        var startEndDate = await _dataManagementService.GetStartEndDate();
        ViewBag.StartDate = startEndDate.Item1;
        ViewBag.EndDate = startEndDate.Item2;
        return View();
    }


    [HttpGet]
    [Route("Data")]
    public async Task<ActionResult<DataTable>> Data(string measuringPoint, DateTime startDate, DateTime endDate)
    {
        var res = await _dataManagementService.GetSamplesDt(startDate, endDate, measuringPoint, null);
        return res != null ? Ok(res) : NotFound();
    }
}

PowerQualityManageService/Views/Preview/CreateParameterName.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div id="overlay"></div>

<div id="CreateNameForm" class="popup-form">
    <h2>Wybierz parametr</h2>
    <div class="p-4 bg-secondary">
        <div class="row">
            <div class="col-md-3"> </div>
            <div class="col-md-6">
                <div class="form-group">
                    <select id="val1" class="form-control">
                        <option value=null>Wskaż Typ</option>
                        <option value="Date">Data i czas</option>
                        <option value="Flagging">Flaga</option>
                        <option value="Voltage">Napięcie</option>
                        <option value="Current">Natężenie</option>
                        <option value="Power">Moc</option>
                        <option value="ApparentPower">Moc pozorna</option>
                        <option value="UnbalancedVoltage">Niesymetryczne napięcie</option>
                        <option value="UnbalancedCurrent">Niesymetryczny prąd </option>
                        <option value="CosPhi">Cosinus kąta fazowego</option>
                        <option value="TanPhi">Tangens kąta fazowego</option>
                        <option value="QV">Jakość Napięcia</option>
                        <option value="PF">Współczynnik mocy</option>
                        <option value="HarmonicVoltage">Harmoniczne napięcia</option>
                        <option value="THD">Całkowite zniekształcenia harmoczniczne</option>
                        <option value="LongTermPercebilility">długoterminowa percepcyjność</option>
                        <option value="ShortTermPercebilility">krótkoterminowa percepcyjność</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3"> </div>
            <div class="col-md-6">
                <div class="form-group">
                    <select id="val2" class="form-control">
                        <option value=null>Wskaż rodzaj pomiaru</option>
                        <option value=null>Nie dotyczy</option>
                        <option value="Phase">Fazowe</option>
                        <option value="PhaseToPhase">Międzyfazowe</option>
                        <option value="Neutral">Żyły neutralnej</option>
                        <option value="Total">Całkowite</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3"> </div>
            <div class="col-md-6">
                <div class="form-group">
                    <select id="val3" class="form-control">
                        <option value=null>Wskaż rodzaj wartości</option>
                        <option value=null>Nie dotyczy</option>
                        <option value="Max">Maksymalna</option>
                        <option value="Min">Minimalna</option>
                        <option value="Abs">Wartość bezwzględna</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3"> </div>
        <div class="col-md-3">
            <button id="acceptCreateName" class="btn btn-primary bg-gradient-primary btn-lg w-100" type="button">Zatwierdź</button>
        </div>
        <div class="col-md-3">
            <button id="closeCreateName" class="btn btn-outline-primary btn-lg w-100" type="button">Anuluj</button>
        </div>
    </div>

</div>

</div>

PowerQualityManageService/Views/Preview/Index.cshtml
@using System.Data;
@{

}
<script src="~/js/alerts.js"></script>
@*<script src="~/js/table.js"></script>*@
<script src="~/js/loading.js"></script>

<div class="text-center">
    @*<h1 class="display-4">Podgląd</h1>*@
    <div class="container">
        <div class="row">
            <div id="alertPreview"></div>
        </div>
        <div class="row">
            <div class="col">
                <div class="row">
                    <form method="get" asp-area="" asp-controller="Preview" asp-action="Data">
                        <div class="row">
                            <div class="form-group">
                                <select id="points1"
                                   onchange="if(this.options[this.selectedIndex].value=='customOption'){toggleField(this,'points2');this.selectedIndex='0';}" 
                                   asp-items="@ViewBag.MeasuringPoints" class="form-control">
                                </select>
                                <input id="points2" class="form-control" style="display:none;" onblur="if(this.value==''){toggleField(this,'points1');}" placeholder="Punkt pomiarowy">
                    @*            <input type="text" class="form-control" id="measuringPointPreview" name="measuringPoint" placeholder="Punkt pomiarowy">*@
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <input class="form-control datepicker" placeholder="Data rozpoczęcia" type="datetime-local" id="startDatePreview" name="startDate">
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <input class="form-control datepicker" placeholder="Data rozpoczęcia" type="datetime-local" id="endDatePreview" name="endDate">
                            </div>
                        </div>
                        <div class="row">
                            <button id="search" class="btn btn-primary bg-gradient-primary btn-lg w-100" type="button">Wyszukaj</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-header p-0 mx-3 mt-3 position-relative z-index-1">
                    </div>
                    <div class="card-body pt-2">
                        <a class="card-title h5 d-block text-darker">
                            Wskazówki
                        </a>
                        Aby podejrzeć dane należy: <br />
                        1. Wybrać punkt pomiarowy, po kliknięciu pojawia się lista dostępnych<br />
                        2. Wybrać date początku i końca danych <br />
                        3. Wybrać opcję wyszukaj
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div style="margin-bottom: 20px;"></div>
        </div>
        <div class="row">
            <div class="card">
                <div id="tablePreview" class="table-responsive">
                </div>
            </div>
        </div>
        <div class="row">
            <div style="margin-bottom: 20px;"></div>
        </div>
    </div>
</div>

@section Scripts {
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://npmcdn.com/flatpickr/dist/l10n/pl.js"></script>
    <script>

        //const Polish = require("flatpickr/dist/l10n/pl.ts");
        var startDate = @Html.Raw(Json.Serialize(ViewBag.StartDate));
        var endDate = @Html.Raw(Json.Serialize(ViewBag.EndDate));

        console.log(startDate)
        console.log(endDate)

        flatpickr.localize(flatpickr.l10ns.pl);

        config = {
            enableTime: true,
            dateFormat: "Y-m-d H:i",
            time_24hr: true,
            altInput: true,
            defaultHour: 0,
            minDate: startDate,
            maxDate: endDate
        }

        flatpickr("#startDatePreview", config);
        flatpickr("#endDatePreview", config);
    </script>
    <script>
        const search = document.getElementById('search');
    </script>
    <script>
        $(function () {
            $('#search').on('click', function (e) {
                e.preventDefault();
                var form = $(this).closest('form');
                var url = form.attr('action');
                var formData = {
                    measuringPoint1: $('#points1').val(),
                    measuringPoint2: $('#points2').val(),
                    startDate: $('#startDatePreview').val(),
                    endDate: $('#endDatePreview').val(),
                };
                console.log('formData:', formData);
                var mp = $('#measuringPointPreview').val()
                console.log('mp:', mp);
                var request = $.ajax({
                    url: url,
                    type: 'GET',
                    data: {
                        measuringPoint: $('#points1').val() || $('#points2').val(),
                        startDate: $('#startDatePreview').val(),
                        endDate: $('#endDatePreview').val()
                    }

                    //processData: false,
                    //contentType: false
                })
                    .done(function (response) {
                        console.log('Sukces:', response);
                        createTable(response, "tablePreview")
                    })
                    .fail(function (error) {
                        console.log('Błąd żądania AJAX:', error);
                        showDangerAlert(error, 'alertPreview')
                    });
                console.log('request:', request);
            });
        });
    </script>
    <script>
        function toggleField(hideObj, showObj) {
            console.log(showObj)
            hideObj.disabled = true;
            hideObj.style.display = 'none';

            show = document.getElementById(showObj)
            show.disabled = false;
            show.style.display = 'inline';
            show.focus();
        }
    </script>
    <script>
        var id = '';
        const overlay = document.getElementById('overlay');
        const createNameForm = document.getElementById('CreateNameForm');

        const acceptCreateNameButton = document.getElementById('acceptCreateName');
        const closeCreateNameButton = document.getElementById('closeCreateName');

        const val1 = document.getElementById('val1');
        const val2 = document.getElementById('val2');
        const val3 = document.getElementById('val3');

        function openDropdowns() {

            overlay.style.display = 'block';
            createNameForm.style.display = 'block';
        }

        function updateConcatenatedValue(id) {
            const concatenatedValuesInput = document.getElementById(id);
            var combinedValue = '';
            if (val1 !== null && val1.value !== undefined && val1.value !== '') {
                combinedValue += val1.value;
            }
            if (val2 !== null && val2 !== undefined && val2.value !== '') {
                combinedValue += '_';
                combinedValue += val2.value;
            }
            if (val3 !== null && val3 !== undefined && val3.value !== '') {
                combinedValue += '_';
                combinedValue += val3.value;
            }
            console.log("UpdateValue")
            console.log(val1.value)
            console.log(val2.value)
            console.log(val3.value)
            concatenatedValuesInput.value = combinedValue;
        }

        acceptCreateNameButton.addEventListener('click', function () {
            updateConcatenatedValue('inputValue')
            overlay.style.display = 'none';
            createNameForm.style.display = 'none';
        });

        closeCreateNameButton.addEventListener('click', function () {
            overlay.style.display = 'none';
            createNameForm.style.display = 'none';
        });
    </script>
    <script>
        function createTable(data, id) {
            var table = document.createElement('table');
            table.className = "table align-items-center mb-0";
            // Tworzenie wiersza nagłówka
            var head = table.createTHead().insertRow();
            for (var key in data[0]) {
                var th = document.createElement('th');
                th.className = "text-columnHeader text-xs font-weight-bolder opacity-7 ps-2"
                th.textContent = key;
                head.appendChild(th);
            }
            // Tworzenie wierszy z danymi
            var body = table.createTBody();
            data.forEach(function (val) {
                var row = body.insertRow();
                for (var key in val) {
                    var cell = row.insertCell();
                    cell.className = "text-dark text-xs"
                    cell.textContent = val[key];
                }
            });

            // Dodanie tabeli do elementu HTML
            var tableContainer = document.getElementById(id);
            tableContainer.appendChild(table);
        }
    </script>
}